config-version: 1.0

modules:
  action-bar:
    enabled: true
    interval: 2
    messages:
      - ''
      - '<rainbow>V'
      - '<rainbow>Vi'
      - '<rainbow>Vis'
      - '<rainbow>Visi'
      - '<rainbow>Visit'
      - '<rainbow>Visit '
      - '<rainbow>Visit w'
      - '<rainbow>Visit ww'
      - '<rainbow>Visit www'
      - '<rainbow>Visit www.'
      - '<rainbow>Visit www.e'
      - '<rainbow>Visit www.ex'
      - '<rainbow>Visit www.exa'
      - '<rainbow>Visit www.exam'
      - '<rainbow>Visit www.examp'
      - '<rainbow>Visit www.exampl'
      - '<rainbow>Visit www.example'
      - '<rainbow>Visit www.example.'
      - '<rainbow>Visit www.example.c'
      - '<rainbow>Visit www.example.co'
      - '<rainbow>Visit www.example.com'
      - '<rainbow>isit www.example.com'
      - '<rainbow>sit www.example.com'
      - '<rainbow>it www.example.com'
      - '<rainbow>t www.example.com'
      - '<rainbow> www.example.com'
      - '<rainbow>www.example.com'
      - '<rainbow>ww.example.com'
      - '<rainbow>w.example.com'
      - '<rainbow>.example.com'
      - '<rainbow>example.com'
      - '<rainbow>xample.com'
      - '<rainbow>ample.com'
      - '<rainbow>mple.com'
      - '<rainbow>ple.com'
      - '<rainbow>le.com'
      - '<rainbow>e.com'
      - '<rainbow>.com'
      - '<rainbow>com'
      - '<rainbow>om'
      - '<rainbow>m'
      - ''
  agreement:
    enabled: true
    on-first-join: true
    on-every-join: false
    on-change: true
    kick-on-disagree: true
    kick-message: |
      <red>You have not agreed to the agreement.</red>
    pages:
      - |
        114514
      - |
        114514
    agree: '<green>Agree</green>'
    disagree: '<red>Disagree</red>'
  anti-break:
    enabled: true
    break-creative-only: true
  anti-interact:
    enabled: true
    creative-only: true
  anti-place:
    enabled: true
    creative-only: true
  boss-bar:
    enabled: true
    interval: 600
    progress: 0.8
    color: RED
    overlay: NOTCHED_10
    messages:
      - '<red>www.example.com'
      - '<aqua>store.example.com'
      - '<green>discord.example.com'
  broadcast:
    enabled: true
    interval: 10000
    messages:
      - |
        <red>Welcome to the server!</red>
        <green>Enjoy your stay!</green>
      - |
        <red>Good luck!</red>
        <green>Have fun!</green>
  clear-chat:
    enabled: true
    on-join: true
  easter-egg:
    enabled: true
  inventory:
    enabled: true
    clear-on-join: false
  join-message:
    enabled: true
    # See groups.yml
  quit-message:
    enabled: true
    # See groups.yml
  potion-effect:
    enabled: true
    clear-on-join: true
    give-on-join: true
    effects:
      - name: SPEED
        duration: 'infinite'
        amplifier: 1
        particles: false
      - name: JUMP_BOOST
        duration: '20'
        amplifier: 0
        particles: true
  spawn:
    enabled: true
    on-join: true
    on-command: true
  void-teleport:
    enabled: true
    level: -64