#   __  ______  _                 __       __  __      __
#  / / / / / /_(_)___ ___  ____ _/ /____  / / / /_  __/ /_
# / / / / / __/ / __ `__ \/ __ `/ __/ _ \/ /_/ / / / / __ \
#/ /_/ / / /_/ / / / / / / /_/ / /_/  __/ __  / /_/ / /_/ /
#\____/_/\__/_/_/ /_/ /_/\__,_/\__/\___/_/ /_/\__,_/_.___/
# v1.0                                powered by KamiLand
# https://www.kamiland.net/plugins/ultimatehub
# https://github.com/KamiLand-Network/UltimateHub
# DeepWiki: https://deepwiki.com/KamiLand-Network/UltimateHub

# Discord: https://discord.gg/7nN4pVZV4f
# Kook: https://kook.vip/BdvsCF

# This plugin supports PlaceholderAPI! Provided you have it installed on your server
# Details: https://www.kamiland.net/plugins/ultimatehub/papi

# Foreword:
# The developer believes that some features (like time-changer, weather-changer)
# can be fully implemented using Minecraft's native gamerule
# Therefore, these options are disabled by default and marked: Native Implementation Available
# We recommend users prioritize native Minecraft solutions to reduce server load

# Configuration file version, not equal to plugin version
# DO NOT change this, the plugin will automatically detect and update configuration versions
# If you change this, the plugin may malfunction
config-version: 1.0

