#   __  ______  _                 __       __  __      __
#  / / / / / /_(_)___ ___  ____ _/ /____  / / / /_  __/ /_
# / / / / / __/ / __ `__ \/ __ `/ __/ _ \/ /_/ / / / / __ \
#/ /_/ / / /_/ / / / / / / /_/ / /_/  __/ __  / /_/ / /_/ /
#\____/_/\__/_/_/ /_/ /_/\__,_/\__/\___/_/ /_/\__,_/_.___/
# v1.0                                powered by KamiLand
# https://www.kamiland.net/plugins/ultimatehub
# https://github.com/KamiLand-Network/UltimateHub
# DeepWiki: https://deepwiki.com/KamiLand-Network/UltimateHub

# Discord: https://discord.gg/7nN4pVZV4f
# Kook: https://kook.vip/BdvsCF

# This plugin supports PlaceholderAPI! Provided you have it installed on your server
# Details: https://www.kamiland.net/plugins/ultimatehub/papi

# Foreword:
# The developer believes that some features (like time-changer, weather-changer)
# can be fully implemented using Minecraft's native gamerule
# Therefore, these options are disabled by default and marked: Native Implementation Available
# We recommend users prioritize native Minecraft solutions to reduce server load

# Configuration file version, not equal to plugin version
# DO NOT change this, the plugin will automatically detect and update configuration versions
# If you change this, the plugin may malfunction
config-version: 1.0

# Module configurations
modules:
  # Action bar messages
  # Requires permission: ultimatehub.action-bar (enabled by default)
  action-bar:
    # Whether enabled (applies to all below)
    enabled: true
    # Refresh interval in ticks
    # In Minecraft, 1 second = 20 ticks
    # Therefore 1 tick = 0.05 seconds
    interval: 2
    # Text displayed in action bar, shown in sequence
    # All text formats in this plugin use MiniMessage, see https://docs.advntr.dev/minimessage/format.html
    # Or our brief documentation: https://www.kamiland.net/plugins/ultimatehub/mini-message
    # You can edit and preview MiniMessage text online here: https://webui.advntr.dev
    messages:
      - ''
      - '<rainbow>V'
      - '<rainbow>Vi'
      - '<rainbow>Vis'
      - '<rainbow>Visi'
      - '<rainbow>Visit'
      - '<rainbow>Visit '
      - '<rainbow>Visit w'
      - '<rainbow>Visit ww'
      - '<rainbow>Visit www'
      - '<rainbow>Visit www.'
      - '<rainbow>Visit www.e'
      - '<rainbow>Visit www.ex'
      - '<rainbow>Visit www.exa'
      - '<rainbow>Visit www.exam'
      - '<rainbow>Visit www.examp'
      - '<rainbow>Visit www.exampl'
      - '<rainbow>Visit www.example'
      - '<rainbow>Visit www.example.'
      - '<rainbow>Visit www.example.c'
      - '<rainbow>Visit www.example.co'
      - '<rainbow>Visit www.example.com'
      - '<rainbow>isit www.example.com'
      - '<rainbow>sit www.example.com'
      - '<rainbow>it www.example.com'
      - '<rainbow>t www.example.com'
      - '<rainbow> www.example.com'
      - '<rainbow>www.example.com'
      - '<rainbow>ww.example.com'
      - '<rainbow>w.example.com'
      - '<rainbow>.example.com'
      - '<rainbow>example.com'
      - '<rainbow>xample.com'
      - '<rainbow>ample.com'
      - '<rainbow>mple.com'
      - '<rainbow>ple.com'
      - '<rainbow>le.com'
      - '<rainbow>e.com'
      - '<rainbow>.com'
      - '<rainbow>com'
      - '<rainbow>om'
      - '<rainbow>m'
      - ''

  # Player agreement
  agreement:
    enabled: true
    # Open agreement when player joins for the first time
    on-first-join: true
    # Open agreement every time player joins
    on-every-join: false
    # Open agreement when agreement changes
    # Requires privileged player/console to use command /agreement change
    on-change: true
    # Delay between player joining and opening agreement (in ticks)
    delay: 100
    # Prevent players from closing agreement book
    prevent-close: true
    # Kick player if agreement signing times out
    kick-on-timeout: true
    # Agreement timeout duration (in ticks)
    timeout: 1200
    # Kick player if they disagree with agreement
    kick-on-disagree: true
    # Kick message if player is kicked
    kick-message: |
      <red>You have not agreed to the agreement.</red>
    # Agreement book page contents
    pages:
      - |
        114514
      - |
        114514
    # Reject button
    # This is standard MiniMessage format as described above
    # Equivalent to player executing /agreement reject
    reject: '<click:run_command:'/agreement reject'><hover:show_text:'<gray>Click to reject the player agreement'><red>Reject</hover></click>'
    # Agree button
    # Equivalent to player executing /agreement agree
    agree: '<click:run_command:'/agreement agree'><hover:show_text:'<gray>Click to agree to the player agreement'><green>Agree</hover></click>'

  # Prevent block breaking
  # Foreword:
  # UltimateHub is not a professional world protection plugin and lacks comprehensive protection features
  # Developer's limited understanding of game mechanics may allow bypasses in certain scenarios
  # Therefore, we recommend using professional world protection plugins like WorldGuard: https://modrinth.com/plugin/worldguard
  # Bypass permission: ultimatehub.anti-break.bypass (admins have by default)
  anti-break:
    enabled: true
    # Only allow creative mode players to break blocks
    # If enabled, even players with bypass permission cannot break blocks in non-creative mode
    # Without bypass permission, creative players still cannot break blocks
    # (Same applies below)
    break-creative-only: true

  # Prevent player interactions
  # Bypass permission: ultimatehub.anti-interact.bypass (admins have by default)
  anti-interact:
    enabled: true
    creative-only: true

  # Prevent block placing
  # Bypass permission: ultimatehub.anti-place.bypass (admins have by default)
  anti-place:
    enabled: true
    creative-only: true

  # Prevent item dropping
  # Bypass permission: ultimatehub.anti-drop.bypass (admins have by default)
  anti-drop:
    enabled: true
    creative-only: true

  # Prevent hunger
  # Requires permission: ultimatehub.anti-hunger (enabled by default)
  anti-hunger:
    enabled: true

  # Prevent player damage
  # Requires permission: ultimatehub.anti-damage (enabled by default)
  anti-damage:
    enabled: true

  # Prevent projectiles
  anti-projectile:
    enabled: true
    # Prevent players from shooting projectiles
    anti-player: false
    # Prevent entities from shooting projectiles
    anti-entity: false

  # Prevent player attacks
  anti-attack:
    enabled: true
    # Prevent PVP (player vs player)
    anti-attack-player: true
    # Prevent PVE (player vs entity)
    anti-attack-entity: true

  # Boss health bar
  # For more information: https://minecraft.wiki/w/Bossbar
  # Requires permission: ultimatehub.boss-bar (enabled by default)
  boss-bar:
    enabled: true
    interval: 20
    # BossBar progress display
    # Maximum 1, minimum 0
    # Example: 0.8 shows 80% health
    progress: 0.8
    # BossBar color (not name color)
    color: RED
    # BossBar style
    overlay: NOTCHED_10
    # BossBar display name
    messages:
      - '<red>www.example.com'
      - '<aqua>www.example.com'
      - '<green>www.example.com'
      - '<yellow>www.example.com'

  # Broadcast messages
  # Receive permission: ultimatehub.broadcast.notify (enabled by default)
  broadcast:
    enabled: true
    interval: 1800
    # Using MiniMessage properly can implement complex click/hover effects
    messages:
      - |
        <red>Welcome to the server!</red>
        <green>Enjoy your stay!</green>
      - |
        <red>Good luck!</red>
        <green>Have fun!</green>

  # Clear player chat
  # Works by sending 100 empty messages when player joins
  # Note: May not work if players use mods with Chat Filter or Infinite Chat History
  # For reliable chat clearing, use F3+D (official Minecraft shortcut)
  # Bypass permission: ultimatehub.clear-chat.bypass (admins have by default)
  clear-chat:
    enabled: true
    # Clear on player join
    on-join: true

  # Easter egg features, see easter-eggs.yml
  easter-egg:
    enabled: true

  # Inventory module
  # Bypass permission: ultimate.inventory.bypass (admins have by default)
  inventory:
    enabled: true
    # Clear inventory on join
    # Disabled by default to prevent accidental item loss
    clear-on-join: false
    # Clear inventory on quit
    clear-on-quit: false
    # Give defined items on join (see items.yml)
    give-on-join: false
    # Give defined items on quit (see items.yml)
    give-on-quit: false

  # Join/quit messages
  # Some servers may show different messages based on player groups
  # Configuration: see groups.yml
  join&quit-message:
    enabled: true

  # Potion effects
  # Requires permission: ultimatehub.potion-effect (not enabled by default)
  potion-effect:
    enabled: true
    # Clear effects on player join
    clear-on-join: true
    # Clear effects on player quit
    clear-on-quit: true
    # Apply effects on player join
    give-on-join: true
    # Potion effect list
    # For effect names, see: https://minecraft.wiki/w/Effect#Effect_list
    # Use effect identifiers from wiki
    effects:
      - name: SPEED
        # Effect duration in seconds. Use 'infinite' for permanent
        duration: 'infinite'
        # Amplifier level (display level - 1)
        amplifier: 1
        # Show particles
        particles: false
      - name: JUMP_BOOST
        duration: '20'
        amplifier: 0
        particles: true

  # Spawn point
  # Requires permission: ultimatehub.spawn
  # Settings: see spawns.yml
  spawn:
    enabled: true
    # Teleport to spawn on join
    on-join: true
    # Teleport to spawn on /spawn command
    on-command: true

  # Time changer
  # Lock time to specific value
  # (Native implementation available)
  time-changer:
    enabled: false
    time: 6000

  # Weather changer
  # Lock weather
  # (Native implementation available)
  weather-changer:
    enabled: false
    weather: clear

  # Void protection
  void-teleport:
    enabled: true
    # Protection level - players below this Y level get teleported
    # Players teleport to spawn point (if set)
    # Players teleport to bed/respawn anchor (if set)
    # Players teleport to world spawn (if neither set)
    level: -64
