#    __ __                _ __  __      __
#   / //_/___ _____ ___  (_) / / /_  __/ /_
#  / ,< / __ `/ __ `__ \/ / /_/ / / / / __ \
# / /| / /_/ / / / / / / / __  / /_/ / /_/ /
#/_/ |_\__,_/_/ /_/ /_/_/_/ /_/\__,_/_.___/


# v1.0                                powered by KamiLand
# https://www.kamiland.net/plugins/kamihub
# https://github.com/KamiLand-Network/KamiHub
# DeepWiki: https://deepwiki.com/KamiLand-Network/KamiHub

# Discord: https://discord.gg/7nN4pVZV4f
# Kook: https://kook.vip/BdvsCF

# This plugin supports PlaceholderAPI! Make sure it is installed on your server.
# See: https://www.kamiland.net/plugins/kamihub/papi

# Configuration file version (not the same as plugin version)
# Do NOT change this value manually.
# The plugin uses it to detect and upgrade configuration format.
# Modifying this value may cause the plugin to malfunction.
config-version: 1.0

# Auto check for updates
check-for-updates: true

# Data source settings
datasource:
  # Storage driver type
  # Currently supported: MySQL, H2
  storage: H2
  table-prefix: 'kh_'
  mysql:
    host: 'localhost'
    port: 3306
    database: 'minecraft'
    username: 'kamihub'
    password: 'UrPasswdHere'
    params: '?useSSL=false&useUnicode=true&characterEncoding=UTF-8'
  h2:
    # H2 connection (file mode)
    file: './plugins/KamiHub/data/storage'
    username: 'kamihub'
    # H2 mode allows empty password by default.
    # If you want to enable password protection for security,
    # append this to the params value:
    # ;CIPHER=AES;IFEXISTS=TRUE
    password: ''
    params: ';MODE=MySQL;FILE_LOCK=SOCKET;TRACE_LEVEL_FILE=0;DATABASE_TO_UPPER=FALSE'
  connection-pool:
    # Connection pool settings
    # Maximum pool size (recommended: CPU cores * 2 + disk count)
    maximum-pool-size: 20
    # Minimum idle connections (recommended: 1/4 of max pool size)
    minimum-idle: 5
    # Connection timeout (ms, suggested: 3000–5000)
    connection-timeout: 3000
    # Idle timeout (ms, default: 5 minutes)
    idle-timeout: 300000
    # Maximum lifetime of a connection (ms, default: 30 minutes)
    max-lifetime: 1800000
    # Validation timeout (ms)
    validation-timeout: 1000
    # Leak detection
    # Leak detection threshold (ms)
    leak-detection-threshold: 30000
    # Recommended to disable auto-commit
    auto-commit: false
